services:
  postgres:
    image: postgres:17.5
    container_name: pg-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: arya
      POSTGRES_DB: goconnect
    volumes:
      - ps-data:/var/lib/postgresql/data
      - ./dataschema/full_dump.sql:/docker-entrypoint-initdb.d/01-schema.sql 

  valkey:
    image: valkey/valkey:7.2
    container_name: valkey
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data

  backend:
    build: ./backend
    container_name: go-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: arya
      DB_NAME: goconnect
      REDIS_ADDR: valkey:6379
    depends_on:
      - postgres
      - valkey

volumes:
  ps-data:
  valkey-data: