apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-backend
  template:
    metadata:
      labels:
        app: go-backend
    spec:
      containers:
        - name: go-backend
          image: goconnect-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: pg-db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: arya
            - name: DB_NAME
              value: goconnect
            - name: REDIS_ADDR
              value: valkey:6379
---
apiVersion: v1
kind: Service
metadata:
  name: go-backend
spec:
  selector:
    app: go-backend
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
