apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: goconnect
            - name: DB_PASSWORD
              value: arya
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: REDIS_ADDR
              value: valkey:6379
          image: goconnect-backend:latest
          name: go-backend
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
