apiVersion: v1
data:
  full_dump.sql: |+
    --
    -- PostgreSQL database dump
    --

    -- Dumped from database version 17.5
    -- Dumped by pg_dump version 17.5

    SET statement_timeout = 0;
    SET lock_timeout = 0;
    SET idle_in_transaction_session_timeout = 0;
    SET transaction_timeout = 0;
    SET client_encoding = 'UTF8';
    SET standard_conforming_strings = on;
    SELECT pg_catalog.set_config('search_path', '', false);
    SET check_function_bodies = false;
    SET xmloption = content;
    SET client_min_messages = warning;
    SET row_security = off;

    SET default_tablespace = '';

    SET default_table_access_method = heap;

    --
    -- Name: posts; Type: TABLE; Schema: public; Owner: postgres
    --

    CREATE TABLE public.posts (
        id integer NOT NULL,
        user_id integer,
        url text NOT NULL,
        likes integer DEFAULT 0,
        created_at timestamp without time zone DEFAULT now()
    );


    ALTER TABLE public.posts OWNER TO postgres;

    --
    -- Name: posts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
    --

    CREATE SEQUENCE public.posts_id_seq
        AS integer
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1;


    ALTER SEQUENCE public.posts_id_seq OWNER TO postgres;

    --
    -- Name: posts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
    --

    ALTER SEQUENCE public.posts_id_seq OWNED BY public.posts.id;


    --
    -- Name: users; Type: TABLE; Schema: public; Owner: postgres
    --

    CREATE TABLE public.users (
        id integer NOT NULL,
        username character varying(100) NOT NULL,
        mail character varying(150) NOT NULL,
        password text NOT NULL,
        no_of_post integer DEFAULT 0,
        bio text,
        created_at timestamp without time zone DEFAULT now()
    );


    ALTER TABLE public.users OWNER TO postgres;

    --
    -- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
    --

    CREATE SEQUENCE public.users_id_seq
        AS integer
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1;


    ALTER SEQUENCE public.users_id_seq OWNER TO postgres;

    --
    -- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
    --

    ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


    --
    -- Name: posts id; Type: DEFAULT; Schema: public; Owner: postgres
    --

    ALTER TABLE ONLY public.posts ALTER COLUMN id SET DEFAULT nextval('public.posts_id_seq'::regclass);


    --
    -- Name: users id; Type: DEFAULT; Schema: public; Owner: postgres
    --

    ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


    --
    -- Data for Name: posts; Type: TABLE DATA; Schema: public; Owner: postgres
    --

    COPY public.posts (id, user_id, url, likes, created_at) FROM stdin;
    1	1	testingurl	0	2025-06-30 20:36:00.077127
    2	1	testingurl	0	2025-06-30 20:37:22.434243
    3	1	testingurl	0	2025-06-30 20:38:31.292305
    4	2	testingurl	0	2025-06-30 20:49:52.695306
    5	2	testurl2	0	2025-06-30 20:50:10.810927
    \.


    --
    -- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
    --

    COPY public.users (id, username, mail, password, no_of_post, bio, created_at) FROM stdin;
    1	Suriya	Suriya@gmail.com	testpass234	0	testeryygo	2025-06-30 20:05:46.982356
    2	suresh	Suresh@gmail.com	testpass234	2	testpass	2025-06-30 20:49:38.092266
    3	yuvaraj	uv@gmail.com	testpass1234	0	test	2025-07-04 21:21:46.878433
    5	test	test@gmail.com	testpass1234	0	test	2025-07-04 21:26:40.43457
    9	test2	test2@gmail.com	testpass1234	0	test	2025-07-04 23:17:59.196662
    10	test3	test3gmailcom	testpass1234	0	test	2025-07-05 00:19:47.818541
    \.


    --
    -- Name: posts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
    --

    SELECT pg_catalog.setval('public.posts_id_seq', 13, true);


    --
    -- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
    --

    SELECT pg_catalog.setval('public.users_id_seq', 10, true);


    --
    -- Name: posts posts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
    --

    ALTER TABLE ONLY public.posts
        ADD CONSTRAINT posts_pkey PRIMARY KEY (id);


    --
    -- Name: users users_mail_key; Type: CONSTRAINT; Schema: public; Owner: postgres
    --

    ALTER TABLE ONLY public.users
        ADD CONSTRAINT users_mail_key UNIQUE (mail);


    --
    -- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
    --

    ALTER TABLE ONLY public.users
        ADD CONSTRAINT users_pkey PRIMARY KEY (id);


    --
    -- Name: posts posts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
    --

    ALTER TABLE ONLY public.posts
        ADD CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


    --
    -- PostgreSQL database dump complete
    --

kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: db
  name: db-cm1
