apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: valkey
  name: valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: valkey
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: valkey
    spec:
      containers:
        - image: valkey/valkey:7.2
          name: valkey
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: valkey-data
      restartPolicy: Always
      volumes:
        - name: valkey-data
          persistentVolumeClaim:
            claimName: valkey-data
